### ISSUE TITLE
Using postgres schemas with migrations.

### ISSUE THREAD

**Issue by fabiogibson** [rust-db/barrel#34]
Hello,

Please, Is there a way to use postgres schemas when generating migrations? I mean something like:

> CREATE TABLE schema.table_name (...

Thanks

**Comment by spacekookie** [comment]
Hey there!

No, unfortunately currently that's not possible. But the internals of `barrel` are being partially re-written right now. So that's definitely something that should be made possible soon!

I'll leave this issue open as a tracking issue for the feature :sparkles:

**Comment by spacekookie** [comment]
Closing this issue because it's possible to use schemas since `0.5.3`:

```rust
let mut m = Migration::new();
m.schema("my_schema");
m.alter_table("users", |t| {
  t.add_column("cool", types::boolean());
});
```
