### ISSUE TITLE
SQLite: Rename Table does not work to superfluous schema name

### ISSUE THREAD

**Issue by mavilein** [rust-db/barrel#65]
Right now barrel generates the following SQL for renaming a table for SQLite when a schema is used. However this is invalid syntax according to: https://www.sqlite.org/lang_altertable.html
```
ALTER TABLE "schema"."new_Author" RENAME TO "schema"."Author";
```

Instead it should be the following. The schema name must be omitted in the to portion.
```
ALTER TABLE "schema"."new_Author" RENAME TO "Author";
```

**Comment by spacekookie** [comment]
On May 17, 2019 9:39:00 AM UTC, mavilein <notifications@github.com> wrote:
>
>Right now barrel generates the following SQL for renaming a table for
>SQLite when a schema is used. However this is invalid syntax according
>to: https://www.sqlite.org/lang_altertable.html
>```
>ALTER TABLE "schema"."new_Author" RENAME TO "schema"."Author";
>```
>
>Instead it should be the following. The schema name must be omitted in
>the to portion.
>```
>ALTER TABLE "schema"."new_Author" RENAME TO "Author";
>```

Thanks for this bug report.

I'm gonna push an update today, probably this evening.
