### ISSUE TITLE
Support Creation of Indexes

### ISSUE THREAD

**Issue by mavilein** [rust-db/barrel#79]
It should cater for support of different index types: Normal, Unique, later on maybe Text Search.

Our workaround in the Prisma codebase: https://github.com/prisma/prisma-engine/blob/master/libs/sql-schema-describer/tests/introspection_tests.rs#L407

**Comment by tomhoule** [comment]
I think this is implemented as of the latest release.

**Comment by spacekookie** [comment]
It is indeed! Needs better docs and tests maybe https://docs.rs/barrel/0.6.5/barrel/types/fn.index.html
