### ISSUE TITLE
Insert statement

### ISSUE THREAD

**Issue by danipozo** [rust-db/barrel#85]
I can't find a method to generate an insert statement. Is this not supported? Furthermore, is there a list of supported SQL statements?

**Comment by spacekookie** [comment]
Hey, sorry I have been kinda awol recently!

In case it's still relevant, or if someone finds this: barrel only generates migrations, it's not an ORM or even query builder. You should use something like diesel (or just use a a database adapter directly)

**Comment by danipozo** [comment]
Ok, I understand, but are insert statements completely excluded from migrations? You might want a table to have some initial values after a migration.

**Comment by spacekookie** [comment]
You can set default values on a column but otherwise you need to use an actual query builder to do anything more fancy.
