### ISSUE TITLE
diesel integration is broken (custom_attribute and rustfmt_skip)

### ISSUE THREAD

**Issue by ejmg** [rust-db/barrel#94]
Hi there,

It appears that diesel integration has been broken again. Installing diesel_cli with the feature flag for barrel migrations gives two errors, one for `custom_attributes` no longer being a supported feature and another for `rustfmt_skip` not being found. 

The full error message is provided below:

```
error[E0557]: feature has been removed
  --> /<snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/barrel-0.2.0/src/lib.rs:70:12
   |
70 | #![feature(custom_attribute)]
   |            ^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in favor of `#![register_tool]` and `#![register_attr]`

error: cannot find attribute `rustfmt_skip` in this scope
  --> /<snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/barrel-0.2.0/src/backend/pg.rs:38:11
   |
38 |         #[rustfmt_skip] /* This shouldn't be formatted. It's too long */
   |           ^^^^^^^^^^^^
```
- toolchain: `rustc 1.42.0-nightly (cd1ef390e 2020-01-31)`

I'm not familiar with the barrel codebase, but understand that keeping any software library up to date is a struggle in of itself. If I can be of help to fix this, I would love to lend a hand, if only but with some direction with how to proceed with the breaking change on `custom_attribute` and the error generated by `rustfmt_skip`.

**Comment by pksunkara** [comment]
That's using barrel@0.2 which is very old. Diesel release itself is more than an year old. I have made a PR to diesel so I can use it directly from the git repository which should fix the issue. https://github.com/diesel-rs/diesel/pull/2316

**Comment by ejmg** [comment]
Sweet! Thanks for the comment and PR :slightly_smiling_face:
